### ISSUE TITLE
Normalize adata (found only log1p)

### ISSUE THREAD

**Issue by rushin682** [mahmoodlab/HEST#15]
Hi Guillaume,

Thanks for the brilliant resource! 

Regarding the normalization process during benchmarking (for the paper benchmarks), is the spot only logarithamized (log1p) or is it normalised (sc.pp.normalize_total()) + sc.pp.log1p?

I am asking because in the code [here](https://github.com/mahmoodlab/HEST/blob/a2aae26b4e0a35987a2094bf8ff819e94c64b984/src/hest/bench/data_modules/st_dataset.py#L11), it seems it's only log1p. Is this intentional?

Thanks for your help. Looking forward to using the benchmark!

**Comment by guillaumejaume** [comment]
Exploring additional normalization strategies and their downstream impact would be valuable. It seems no consensus has been reached yet. In addition, exploring the impact of the downstream classification model is also interesting. We explored random forest and ridge regression and observed large variations.
