### ISSUE TITLE
Why don't we use all the samples to construct the benchmark?

### ISSUE THREAD

**Issue by huangtinglin** [mahmoodlab/HEST#27]
Thanks for the valuable work and dataset, which inspires me a lot.

I found that only 86 samples were used for benchmarking, while the whole dataset included around 1K samples. I wonder if we can construct a larger benchmark by incorporating the whole HEST-1K dataset.

**Comment by guillaumejaume** [comment]
Hi, thanks for your interest in our work. It is definitively possible to construct a larger benchmark. HEST-Benchmark was built based on human cancer samples, whereas HEST-1k includes mouse samples, healthy cases, and samples with other diseases. Still, we encourage other researchers to explore other tasks that could be developed from HEST-1k, such as enlarging HEST-Benchmark.

**Comment by huangtinglin** [comment]
That makes sense! Thank you for answering.
