### ISSUE TITLE
TENX98 and TENX97 don't have pixel/array coordinates

### ISSUE THREAD

**Issue by KalinNonchev** [mahmoodlab/HEST#28]
Hi,
thank you for providing these valuable datasets. I have been exploring the breast cancer IDC dataset and noticed that samples TENX98 and TENX97 do not have pixel and array coordinates in their `obs` metadata. Could you clarify whether these coordinates are missing, or if this might be due to a preprocessing error?
Thank you in advance!
Best,

**Comment by pauldoucet** [comment]
Hello Kalin,
For now we store the spot coordinates in the `obsm['spatial']` for compatibility with some core scanpy methods such as `sc.pl.spatial`. First column and second column in `obsm['spatial']` are x and y pixel coordinate in the full resolution H&E respectively.

**Comment by KalinNonchev** [comment]
Ok, I wrongly assumed that I would be able to find this also in the `obs` for all samples (named as `array_row`; `array_col`, `pxl_row_in_fullres`, `pxl_col_in_fullres`). Thanks
