### ISSUE TITLE
Import Error: ModuleNotFoundError for vision_transformer_latest

### ISSUE THREAD

**Issue by oyjr** [mahmoodlab/HEST#31]
When trying to run the predict_expression.py script, I encountered an import error. The error suggests that the module vision_transformer_latest is missing, but I can't find this file in the project directory.
Are there any additional setup steps or dependencies I might have missed?
Thank you for your help in resolving this issue.

**Comment by oyjr** [comment]
`Traceback (most recent call last):
  File "[...]/src/hest/bench/training/predict_expression.py", line 23, in <module>
    from hest.bench.cpath_model_zoo.builder import get_encoder
  File "[...]/src/hest/bench/__init__.py", line 2, in <module>
    from .training.predict_expression import benchmark_encoder
  File "[...]/src/hest/bench/training/predict_expression.py", line 23, in <module>
    from hest.bench.cpath_model_zoo.builder import get_encoder
  File "[...]/src/hest/bench/cpath_model_zoo/__init__.py", line 1, in <module>
    from .models import *
  File "[...]/src/hest/bench/cpath_model_zoo/models/__init__.py", line 1, in <module>
    from .vision_transformer_latest import *
ModuleNotFoundError: No module named 'hest.bench.cpath_model_zoo.models.vision_transformer_latest'`

**Comment by pauldoucet** [comment]
Good morning, sorry for the inconvenience.
We just pushed a fix, can you do pull the new update please?

Let me know how it goes

**Comment by oyjr** [comment]
Thank you for the quick fix! I've pulled the new update, and it has resolved the initial import error. I found that I needed to remove two more import statements to get everything working:

In [...]/src/hest/bench/cpath_model_zoo/models/custom_weight_loaders.py, line 6:
from .vision_transformer_latest import resize_pos_embed
In [...]/src/hest/bench/cpath_model_zoo/builder.py, line 2:
from .models.vision_transformer_custom import vit_large_w_pooler

After removing these two imports, the script ran successfully. Thank you!!

**Comment by pauldoucet** [comment]
Thanks for the feedback!

We're currently working on a complete cleanup of the benchmark and the addition of a couple new models too. I will create a pull request today,

Best,

Paul
