### ISSUE TITLE
Pre-processed data for the multimodal representation learning task

### ISSUE THREAD

**Issue by hathawayxxh** [mahmoodlab/HEST#34]
Hi Authors,

Thanks for your excellent work. I am very interested in developing algorithms based on the HEST-1k database. 
I would like to know how to get access to the pre-processed data for the multimodal representation learning task, which corresponds to the experimental results in Table 2.
I look forward to your reply.

Best,
Xiaohan

**Comment by guillaumejaume** [comment]
Hi Xiaohan, experiments presented in Table 2 are based on all human Xenium breast samples (see HEST-1k metadata). You can query those samples using our download pipeline (see tutorial 1). We only did log1p normalization. The code for contrastive alignment is not public yet, but it is quite standard.

**Comment by hathawayxxh** [comment]
Hi Guillaume, 
Thanks for your prompt reply. I have checked the metadata and noticed there are six Xenium invasive breast cancer samples (i.e., TENX 94-99). However, you indicated that you used five samples to finetune the CONCH model. Could you please indicate which five samples you used for finetuning? Thanks.

**Comment by guillaumejaume** [comment]
You can refer to the patient entry in the metadata.

**Comment by hathawayxxh** [comment]
Thanks, I will try.
