### ISSUE TITLE
About cell type information

### ISSUE THREAD

**Issue by nkuweili** [mahmoodlab/HEST#35]
Hi authors!

   Thanks for your brilliant work! I also want to know where we can find the meta data of cells like **cell type** in HEST? 
   Thanks! I am looking forward to your reply.

Best,
Wei

**Comment by guillaumejaume** [comment]
Hi, the CellViT output is in https://huggingface.co/datasets/MahmoodLab/hest/tree/main/cellvit_seg. You can directly use the GEOJSON to viz the segmentation/classification with QuPath. Please note that CellViT output is not ground truth. Let me know if you have additional questions.

**Comment by nkuweili** [comment]
Thanks Guillaume, @guillaumejaume 

     Great. I fully agree with you that CellViT enables joint instance segmentation and classifcation of each nucleus into fve classes. While for those datasets which were provided with like "ground-truth" labels labeled by their pathologist, did HEST include these information? (I do agree that this type of information may not be easily accessible to collect.)
    Thanks for your time:)

**Comment by guillaumejaume** [comment]
There is not true ground truth shared as part of HEST at the moment. Cell phenotyping using the ST profile is doable. We will make a release with those in the next couple of weeks.

**Comment by nkuweili** [comment]
Great and thanks for detailed reply!
