### ISSUE TITLE
Matching cell type annotations with AnnData gene expression vectors

### ISSUE THREAD

**Issue by merelkuijs** [mahmoodlab/HEST#38]
Hi all,

Thanks for providing this resource. Is there a way to match CellViT's cell type labels, obtained from the images, with the gene expression vectors in the AnnData object?

Merel

**Comment by guillaumejaume** [comment]
Hi Merel, you will have to implement a dedicated function, but all the information is provide:
- coords of each CellViT cell (and cell type)
- coords of each ST spot

The function would be very similar to: https://github.com/mahmoodlab/HEST/blob/minor-release/src/hest/batch_effect.py#L70

**Comment by merelkuijs** [comment]
We have Xenium data, so I wrote code to match each AnnData row to a single cell in the pathology slide. I did observe that the distance to the nearest neighbor in the other modality can be quite large, presumably because the Xenium slide and the area used for imaging don't perfectly overlap. For this reason, I'm not very confident that the transferred labels are correct.

I'll drop the code here in a comment once I've tested it, if anyone else is interested. However, I think traditional cell typing (based on gene expression) is going to be a more reliable source of labels than the image-to-anndata label transfer.

**Comment by pauldoucet** [comment]
Hi @merelkuijs,
We're actively working on providing the .h5ad with a pooling of transcripts per cells. We're trying to upload them by the end of this week

**Comment by xiachenrui** [comment]
Hi @pauldoucet ，

Can we access single cell level expression data of Xenium now.

Best!

**Comment by guillaumejaume** [comment]
Hi @xiachenrui, release will be announce end of next week with additional samples too. Stay tuned.

**Comment by pauldoucet** [comment]
Hi @merelkuijs,

The aligned transcripts are now available [on HF](https://huggingface.co/datasets/MahmoodLab/hest/tree/main) along with 121 new samples. 

Please follow [tutorial 2](https://github.com/mahmoodlab/HEST/blob/main/tutorials/2-Interacting-with-HEST-1k.ipynb) in order to link each transcript to its corresponding cell.

We apologize for coming back to you this late, registration took more time than expected.

**Comment by xiachenrui** [comment]
Thanks for your great works!

**Comment by merelkuijs** [comment]
I noticed that all data folders on Hugging Face were updated, except for the wsis folder. Will WSIs be made available for new samples?

**Comment by pauldoucet** [comment]
It's a mistake from my side, I'm uploading the WSI folder now.

Sorry about that

**Comment by pauldoucet** [comment]
Done, @merelkuijs

**Comment by merelkuijs** [comment]
Thanks, both for uploading the WSIs and responding so swiftly!
