### ISSUE TITLE
negative value in adata.obsm['spatial']

### ISSUE THREAD

**Issue by xiachenrui** [mahmoodlab/HEST#40]
Hi,

Thanks for your great works !

I found in `TENX92` sample's data (read as AnnData format by scanpy), some spots have negative value. 

```python
import scanpy as sc
adata = sc.read_h5ad('./hest/st/TENX92.h5ad')
adata.obsm['spatial'].min()
# I got "-139"

```

Does this phenomenon mean the spot is not inside the H&E image ? Any clarification will be helpful !

Best,

Chen-Rui

**Comment by pauldoucet** [comment]
Hi @xiachenrui,
Correct some of the spots in TENX92 are outside the image, this can be visualized on `spatial_plots/TENX92_spatial_plots`.

These spots are filtered out during patching (in `patches/` or using `dump_patches()`)


![TENX92_spatial_plots](https://github.com/user-attachments/assets/52cb33e0-f259-4db1-b797-aef2653da8cb)

**Comment by xiachenrui** [comment]
Thanks for your quick response !
