### ISSUE TITLE
BCNB dataset

### ISSUE THREAD

**Issue by hathawayxxh** [mahmoodlab/HEST#44]
Hi Authors,

Thanks for the great work. I am curious about the BCNB dataset that you used in the "multimodal representation learning" task. The dataset provides both the WSIs and patches from the tumor region. Did you use the patches from the tumor region or segmented patches from the WSI?

Best,
Xiaohan

**Comment by guillaumejaume** [comment]
Hi, we used the WSI. To build a slide embedding, we simply took the average of the patch embeddings (CONCH and CONCH-FT) constituting the WSI.

**Comment by hathawayxxh** [comment]
Did you use the CLAM toolkit to divide the WSI into patches? or use the patches provided by the BCNB dataset?

**Comment by guillaumejaume** [comment]
We used a deep-learning based tissue segmentation. You can also use the CLAM toolbox.

**Comment by hathawayxxh** [comment]
In the official BCNB dataset, they also provided the paper_patches.zip which contains the patches from the annotated tumor regions. Can we just use those patches to extract the WSI feature?

![image](https://github.com/user-attachments/assets/659973ab-322a-48ff-8337-62e18b6682c0)

**Comment by guillaumejaume** [comment]
I have never used the patches provided by BCNB, only the WSIs. I suppose you can extract patch embeddings from these too. For reference, as part of HEST-Benchmark, we integrated a series of patch encoders, such as UNI, GigaPath, etc., see https://github.com/mahmoodlab/HEST/blob/main/src/hest/bench/cpath_model_zoo/inference_models.py

**Comment by hathawayxxh** [comment]
Thanks. I will try to extract patch embeddings from the provided paper_patches.zip. If we segment the tissue and divide the patches with different methods, the resulting patches from the same dataset might be different. I am curious about how to get consistent results with different patching methods?

**Comment by guillaumejaume** [comment]
feel free to use: https://github.com/mahmoodlab/MADELEINE/blob/main/bin/extract_patch_embeddings.py

**Comment by hathawayxxh** [comment]
Thanks. I will try.
