### ISSUE TITLE
Xenium datasets coordinates

### ISSUE THREAD

**Issue by flyfyyfyy** [mahmoodlab/HEST#46]
Hi,

The Xenium are imaging-based ST technology so that the Xenium dataset's spatial coordinates are not supposed to be grid.
Why does the TENX99 dataset have the grid coordinates. 

I check the raw data from 10x genomics replicate 1, <https://www.10xgenomics.com/datasets/ffpe-human-breast-using-the-entire-sample-area-1-standard>.
The cells matrix in raw data.
<img width="1279" alt="image" src="https://github.com/user-attachments/assets/a210bfbf-930b-4798-83c8-1ccc0e198a39">

And  I only get 280 genes for each spot and 892965 spots in raw data. But 23060 spots in HEST TENX99.
So, how do you guys pre-process the Xenium dataset here?

**Comment by guillaumejaume** [comment]
Hi @flyfyyfyy,

HEST-1k was initially designed to match H&E crops and ST spots. Xenium transcripts have been pooled into pseudo-Visium (squared spots). As it seems that many people are interested in Xenium, we will be releasing aligned H&E with Xenium/DAPI at cell-level + the list of all transcripts.

Having perfect alignment takes time as Xenium explorer tools don't scale well. We are using a sota whole-slide registration instead. More information here: https://github.com/mahmoodlab/HEST/issues/38. 

The release is expected for next Friday.

**Comment by kennethahah** [comment]
Hi @guillaumejaume 

Which sota whole-slide registration tool did you use to align the HE image with Xenium?

**Comment by guillaumejaume** [comment]
A slightly modified version of Valis, https://github.com/MathOnco/valis.

**Comment by guillaumejaume** [comment]
Tutorial has been updated: https://github.com/mahmoodlab/HEST/blob/main/tutorials/2-Interacting-with-HEST-1k.ipynb
