### ISSUE TITLE
About patches in WSI

### ISSUE THREAD

**Issue by Yoyiming** [mahmoodlab/HEST#47]
I would like to know what 'in_tissue' in the Visium data, such as 'INT10', represents in adata. If I want to segment the WSI into patches based on adata's 'pxl_row_in_fullres' and 'pxl_col_in_fullres', should I select the positions where 'in_tissue=0' before performing the segmentation?

**Comment by pauldoucet** [comment]
Hi,
`in_tissue` is a default Spaceranger flag, it doesn't represent anything at the moment as it was just left out during data acquisition. 

The actual tissue segmentation is available in `tissue_seg/` on [HuggingFace].(https://huggingface.co/datasets/MahmoodLab/hest/blob/main/tissue_seg/INT10_contours.geojson)
You can automatically load the tissue segmentation when using `load_hest`, and then patch such that you only keep the patches under tissue as follows:
```
from hest import load_hest

hest_list = load_hest('hest_data', id_list=['INT10'])

patch_save_dir = 'patches'

st = hest_list[0]

st.dump_patches(
    patch_save_dir,
    name='demo',
    target_patch_size=224, # target patch size in 224
    target_pixel_size=0.5 # pixel size of the patches in um/px after rescaling
)
```

**Comment by Yoyiming** [comment]
Thank you very much for your response! It is really helpful.

**Comment by Yoyiming** [comment]
@pauldoucet 
Hello, I have one more question that I am a bit confused about. In the adata, does 'pxl_row_in_fullres' and 'pxl_col_in_fullres' correspond to the width and height in the WSI, respectively? Is the following code correct for obtaining patches?

whole_image = cv2.imread(image_path)
patch = self.whole_image[x-112:x+112, y-112:y+112]

Where x represents 'pxl_row_in_fullres' and y represents 'pxl_col_in_fullres'.

**Comment by Yoyiming** [comment]
Hello, I have one more question that I am a bit confused about. In the
adata, does 'pxl_row_in_fullres' and 'pxl_col_in_fullres' correspond to the
width and height in the WSI, respectively? Is the following code correct
for obtaining patches?

whole_image = cv2.imread(image_path)
patch = self.whole_image[x-112:x+112, y-112:y+112]

Where x represents 'pxl_row_in_fullres' and y represents
'pxl_col_in_fullres'.

**Comment by pauldoucet** [comment]
Hello,
We strongly encourage using `st.adata.obsm['spatial']`, instead of  'pxl_row_in_fullres' and 'pxl_col_in_fullres' which might not be available for every technology.

You can then use the following:
```
xy = st.adata.obsm['spatial'] # Nx2 array, first column is x, second is y
coords = xy[0] # get coordinates of first spot
x, y = coords[0], coords[1]
patch = self.wsi.read_region((x-112, y-112), 0, (224, 224))
```

**Comment by Yoyiming** [comment]
Thank you for your suggestion! I’ll give it a try.

**Comment by pauldoucet** [comment]
I'd also suggest having a look at [2-Interacting-with-HEST-1k.ipynb](https://github.com/mahmoodlab/HEST/blob/main/tutorials/2-Interacting-with-HEST-1k.ipynb)

**Comment by HelloWorldLTY** [comment]
Hi, I found that sometimes .obsm['spatial'] contains float data, and thus it will cause an error for the patching code. Do you think it is ok to use int(x) and int(y) to round the location? Thanks.
