### ISSUE TITLE
What's the relation between coordinates in patches and coordinates in ST data?

### ISSUE THREAD

**Issue by kennethahah** [mahmoodlab/HEST#52]
In each h5 file in the `patches` folder, there is a key called `coords` giving the coordinates of the **top-left** corner of the patch in the full resolution HE image.

In each h5ad file in the `st` folder, the `st.adata.obsm['spatial']` also tells us the coordinates of the spot. Is this coordinate the **center** of the spot? 

How does these two coordinates relate to each other. Let's say it is a ST dataset and so the spot diameter is 100 um. The patch image is 224 x 224 at 0.5um/px (and so 112 um x 112 um). How does the spot lies inside the patch image? Does it sit in the center of the patch? Similar problems arise when we deal with Xenium dataset where you made those 100um side-length pseudo bins. Does those bins sit in the center of the patch? Or the top-left corners of these bins are exactly those top-left corners of the patches?

**Comment by guillaumejaume** [comment]
Yes, both are aligned, you will get a better understanding when looking at this function doing the job: https://github.com/mahmoodlab/HEST/blob/main/src/hest/HESTData.py#L272

**Comment by pauldoucet** [comment]
Hi @kennethahah,
- yes, `st` corresponds to ST data, so st.adata.obsm['spatial'] indicates the center of the spots
- the `coords` key in the `patches/` folder is indeed the top-left corner of each patch associated with a spot. Coordinates of top-left corners are computed in the `HESTData.dump_patches` method, they are computed such that the associated spot lies in the middle of the patch.
- the Xenium bins also sit in the center of the patch. You're correct, with the current pseudo-visium binning method, Xenium bins might be larger than the actual patch. (12um larger for 112um x 112um patches)

We'll release the actual individual transcripts soon. We apologize for the delay, registration takes a bit more time than expected.

**Comment by xiachenrui** [comment]
Hi @pauldoucet,

Could you clarify if WSIs with different mpp were rescaled to same mpp (0.5) when extracting the tiles. In other words, whether all tiles have same mpp ?

Best!

**Comment by pauldoucet** [comment]
Hello,
Yes, they were all rescaled to 0.5um/px

**Comment by xiachenrui** [comment]
Thanks ! @pauldoucet

**Comment by kennethahah** [comment]
Thank you @pauldoucet
