### ISSUE TITLE
Number of cells in human xenium samples

### ISSUE THREAD

**Issue by kotr98** [mahmoodlab/HEST#54]
Hi,

I am currently trying to use the human xenium samples in the HEST1k dataset and downloaded the h5ad files. I was very surprised when I looked at the cell numbers. They ranged between 1000-10.000 cells per sample, which is fairly low for xenium samples in my experience.

For example the sample NCBI884.h5ad has 2521 cells and 541 genes. When looking at the metadata (metadata_NCBI884.json) it states:

id NCBI884
dataset_title Image-based spatial transcriptomics identifies molecular niche dysregulation associated with distal lung remodeling in pulmonary fibrosis
data_publication_date 23-Dec-23
study_link https://www.biorxiv.org/content/10.1101/2023.12.15.571954v2
download_page_link1 https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE250346
spots_under_tissue 2504

but when i look at the publications supplementary files the samples have different names and more cells per sample (tens of thousands). According to the GEO description they also only included 343 genes in their panel, while the h5ad has 541 genes.

Why is the number of cells and gene number so different then the samples in the linked publication and what is the mapping between the sample ids in HEST1k and the GEO ids?

Am I missing something important here?

Thanks in advance.

**Comment by pauldoucet** [comment]
Hi @kotr98,

We provide 2 different segmentations for xenium samples:

- `cellvit_seg/`: contains the cellvit segmentation which is highly dependent on the quality of the H&E staining.
- `xenium_seg/`: contains the segmentation on the DAPI channel, aligned to the H&E image.

When having doubts, we highly recommend visualizing the segmentation with QuPath (we provide .geojson for each sample).
When loading xenium_seg/NCBI884_xenium_cell_seg.geojson in QuPath I see >10'000 nuclei so I assumed that you read the `cellvit_seg/` segmentation. Also this specific dataset was derived from TMA samples, which explains why the tissue area is much smaller than for other Xenium samples.

For the gene panel, xenium also includes negative control probes to evaluate the specificity of the assay (NegControlCodeword_XXXX), as well as unassigned codewords (UnassignedCodeword_XXXX). Feel free to discard those.

For the GEO id, please have a look at the `subseries` column in the [metadata dataframe](https://huggingface.co/datasets/MahmoodLab/hest/blob/main/HEST_v1_1_0.csv), in contains the name of geo sample.

**Comment by kotr98** [comment]
Hi, 
thanks for your clarifications and quick response!

I used the h5ad files in st/.

I assumed the h5ad files in st/ have been created using the transcripts and the xenium cell segmentations.

**Comment by pauldoucet** [comment]
The h5ad in `st/` was created using the transcripts only, it contains pseudo-visium spots, i.e. square bins of 100um per 100um. We did this with multimodal learning in mind at first, in order to have molecular profiles/spots associated to each patch and to ensure a smoother integration with visium samples.

If you are more interested in a pooling per cell, please read the [cell_id column](https://github.com/mahmoodlab/HEST/blob/main/tutorials/2-Interacting-with-HEST-1k.ipynb) in the transcript dataframe. We do not provide the API to do that yet, but we are working on it.
