### ISSUE TITLE
Patches not normalized by pixel size

### ISSUE THREAD

**Issue by yijiangchen** [mahmoodlab/HEST#57]
Hi authors,

First thank you for the great work, but I have some questions regarding the pre-processed patches.

The description claimed that in patches downloaded from the HEST1k dataset, the patches folder contains 256x256 H&E patches (0.5µm/px) extracted around ST spots in a .h5 object optimized for deep-learning. Each patch is matched to the corresponding ST profile (see st/) with a barcode.

However, upon inspection of the patches, it is clear that the length scale / magnification varies from patient to patient. For example, the patches from INT2 and TENX97 are consistent in resolution

**Comment by guillaumejaume** [comment]
The magnification at which the original image was scanned can vary from one sample to another. However, when patching, we take into account the original slide magnification to extract 112 x 112 um image crops at 20x. 

Also, make sure to download the latest version of the patches from HuggingFace. 

Do you mind posting an example showing how the magnification varies from one patch to another? Thanks

**Comment by yijiangchen** [comment]
INT2:![AATAGTCCGTCCCGAC-1](https://github.com/user-attachments/assets/0dc69e25-1a2a-4dbc-b5c1-f23fbfeeedd0)
TENX97:![960](https://github.com/user-attachments/assets/45138c7c-242f-4389-8f8d-9ee459567a38)
TENX79:![AAGCGAGGACTGAGTC-1](https://github.com/user-attachments/assets/4a4b81e4-19d8-4b58-9cbe-9f9640fda312
![AATACTGTGATGCAAT-1](https://github.com/user-attachments/assets/151060d8-340f-4290-9708-592542a8c7c9)
)
TENX30:![AAGGGACAGATTCTGT-1](https://github.com/user-attachments/assets/0818908d-5bd9-45a0-8b33-f7afab595bc0)

Thank you for the response! The examples above shows very obvious magnification discrepancy

**Comment by guillaumejaume** [comment]
Can I see your code? I did a quick test on MEND68, where I re-downloaded the patches (as h5) from the HuggingFace webpage.

```
import h5py
from PIL import Image 
import numpy as np

file_path = 'MEND68.h5'  
with h5py.File(file_path, 'r') as h5file:
    print("Keys in the HDF5 file:", list(h5file.keys()))
    dataset = h5file['img'][:]
    print(dataset.shape)

    for i in range(10):
        img = dataset[i*10]
        img = img.astype(np.uint8) 
        img = Image.fromarray(img)
        img.save('{}.png'.format(i*10))  
```
![0](https://github.com/user-attachments/assets/eac26e42-4e8f-4ecc-98c7-665273d6b696)
![20](https://github.com/user-attachments/assets/7087d5ca-36a1-4bd4-875a-04e682f5e463)
![40](https://github.com/user-attachments/assets/6685507b-0140-4a0b-8c53-cc18e0fabef9)

This returns:

**Comment by guillaumejaume** [comment]
I want to point out that the WSIs are provided at different magnifications (see metadata). Crops of different sizes must be used to patch at the same 20x resolution (112 x 122 um).

**Comment by yijiangchen** [comment]
Just saw the other thread that directly re-downloading the patches would not force replacement the old ones, I think mine were an older version of patches. I'll try to re-download the latest patches and get back to you.

**Comment by guillaumejaume** [comment]
I close the issue for now. Feel free to re-open if you still encounter similar problems.
