### ISSUE TITLE
The function save_spatial_plot does not align the HE image with spots on NCBI784

### ISSUE THREAD

**Issue by kennethahah** [mahmoodlab/HEST#59]
I followed the second tutorial by loading the hest_data for NCBI784 by 
```for st in iter_hest('/project/hest1k/hest_data', id_list=['NCBI784'])```
then I call `st.save_spatial_plot(save_dir)` and it seems that the spots are not aligned with the HE image.

I tried other datasets and they are well-aligned except this one.

<img width="567" alt="Screenshot 2024-10-23 at 11 00 07 AM" src="https://github.com/user-attachments/assets/13b07aac-ee58-42b0-8838-0186a696e2fc">

**Comment by guillaumejaume** [comment]
Thanks for letting us know. We will investigate and make any necessary changes. Do you confirm that all other samples look "normal"? Also, consider pulling the latest version of HEST-1k, which now includes 1,229 samples. Thanks!

**Comment by kennethahah** [comment]
I can't confirm all other samples. I checked some samples, (e.g. `NCBI783`, `NCBI785`, `TENX99`) and they look normal.

I pulled these data in August when the version was `1.0.2`. Today I re-pulled the current version `1.1.0` and redownload some of these data (`meta_df['organ']=='Breast'`). 

I don't know if redownloading existing dataset will overwrite the previously downloaded one.

**Comment by guillaumejaume** [comment]
If the filenames are matching, it won't redownload existing ones. You can modify this behavior in the load_dataset fn from the `datasets` package using the `download_mode` arg, cf.

https://huggingface.co/docs/datasets/v3.0.2/en/package_reference/loading_methods#datasets.load_dataset.download_mode

**Comment by pauldoucet** [comment]
Hi @kennethahah,

Thanks again for letting us know of the issue.
We just re-uploaded the corrected NCBI784 on [the Hugging Face](https://huggingface.co/datasets/MahmoodLab/hest)
