### ISSUE TITLE
Regarding the Number of Patches and Spots in Xenium Dataset

### ISSUE THREAD

**Issue by Yoyiming** [mahmoodlab/HEST#60]
Hi, I noticed that in the Xenium dataset, the number of patches in the patches file is less than the number of spots in the st file. For example, in the TENX133 dataset, there are 3,811 spots, but only 1,377 patches in the TENX133.h5 file. Could you help explain the reason for this difference? Maybe I missed something important.

Thanks in advance!

**Comment by guillaumejaume** [comment]
Hi, 

This is the spatial plot for TENX133: https://huggingface.co/datasets/MahmoodLab/hest/blob/main/spatial_plots/TENX133_spatial_plots.png, 
And this is the patching: https://huggingface.co/datasets/MahmoodLab/hest/blob/main/patches_vis/TENX133_patch_vis.jpg

As you can see, the tissue is not covering 100% of the image, hence the difference. Let me know if unclear.

**Comment by Yoyiming** [comment]
I understand your point now. Thanks again!
