### ISSUE TITLE
Updated figure flipped species counts

### ISSUE THREAD

**Issue by JosephDiPalma** [mahmoodlab/HEST#64]
It appears like the species counts in the updated teaser figure in the readme are wrong (https://github.com/mahmoodlab/HEST/blob/main/figures/fig1a.jpeg).
The counts for human and mouse are flipped.

Code I used to compute this:

```python
import pandas as pd
from collections import Counter

df = pd.read_csv("hf://datasets/MahmoodLab/hest/HEST_v1_1_0.csv")

print(Counter(df.species))
```

**Comment by guillaumejaume** [comment]
thanks for the heads up, i'll modify asap.
