### ISSUE TITLE
Aligning new HE-Xenium data

### ISSUE THREAD

**Issue by alesroger** [mahmoodlab/HEST#74]
Sorry if I've overseen this, but a hint would be very helpful!
Do you provide sample code somewhere to align new Xenium data? In detail, I have unaligned HE WSI and Xenium data available. What's the easiest way to align these (and bring them to the HEST format) with your code?
Thank you!

**Comment by pauldoucet** [comment]
Hi @alesroger,
You can try with [XeniumReader().auto_read(path)](https://hest.readthedocs.io/en/stable/generated/hest.readers.XeniumReader.html#hest.readers.XeniumReader) or with `read()`.

Please make sure to pull the latest version of the hest lib, as we modified several things.

You can then save the HESTData object with `save()`

**Comment by alesroger** [comment]
thank you very much! i will follow up as soon as this works for me and can post the working code, but i cannot say when this will be the case.

close this issue if you wish!

**Comment by guillaumejaume** [comment]
feel free to re-open if needed
